import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import Header from "./components/Header";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Welcome Blog App",
  description: "Generated by create next app",
  keywords: "web development, web design, javascript, react, html, css",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`container px-5 mx-auto min-h-screen overflow-x-hidden ${roboto.className} bg-[#84dd84]`}
      >
        <Header />

        <main>{children}</main>
      </body>
    </html>
  );
}
